plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6,7)'
}

group = 'com.arthurlebgddu41.zipmod'
version = '1.0.0'

base {
    archivesName = 'zipmod'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.level.net.minecraftforge', 'DEBUG'
            mods {
                zipmod {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.level.net.minecraftforge', 'DEBUG'
            args '--nogui'
            mods {
                zipmod {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/main/resources' }

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'      : 'zipmod',
            'Specification-Vendor'     : 'Arthurlebgddu41',
            'Implementation-Title'     : project.name,
            'Implementation-Version'   : jar.archiveVersion,
            'Implementation-Vendor'    : 'Arthurlebgddu41',
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
